### ISSUE TITLE
Flow of the project

### ISSUE THREAD

**Issue by xchopin** [Apereo-Learning-Analytics-Initiative/OpenLRW#39]
Hi,

I saw your interesting new commits but it removed some of my recent contributions.
Did my contributions not fit with the flow of the project?

Regards

**Comment by gryglbrt** [comment]
Hi Xavier,

Yes, I had to back out your pull requests. The structural changes were too disruptive to existing deployments of the software. If you would like to resubmit the pull requests without the structural changes (e.g., changing the directory structure, changing the port, etc) I'll merge again. Otherwise I'll look through the commits at some point soon and let you know which we can accept and which we cannot.

Best,
Gary

**Comment by xchopin** [comment]
Thanks for the feedback.
