### ISSUE TITLE
Swagger does not work anymore

### ISSUE THREAD

**Issue by xchopin** [Apereo-Learning-Analytics-Initiative/OpenLRW#67]
I get an ERR_EMPTY_RESPONSE when I check the website

**Comment by bseclier** [comment]
Hello Gary,
It seems that the swagger is definitively dead.
We'd like to have a list of all routes of openlrw's API. Do you think we can write a text file directly in the openlrw code ? (ie. routes.txt). Or maybe we should update the code (javadoc) in order to generate a new "swagger file" (Idk how it works, sorry).
Thanks for your help,

**Comment by xchopin** [comment]
Stupid as hell lol I am gonna add this in the doc
